import argparse
import csv
from collections import defaultdict
from datetime import datetime


def parse_args():
    parser = argparse.ArgumentParser(
        description="Generate usage summary and prompt export files from usage_logs.csv"
    )
    parser.add_argument(
        "--input",
        default="usage_logs.csv",
        help="Path to usage log CSV generated by app.py",
    )
    parser.add_argument(
        "--summary-output",
        default="usage_summary.csv",
        help="Path to write aggregated usage summary CSV",
    )
    parser.add_argument(
        "--prompts-output",
        default="user_prompts.csv",
        help="Path to write extracted prompt CSV",
    )
    return parser.parse_args()


def load_rows(path):
    with open(path, "r", newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def to_date(ts):
    if not ts:
        return ""
    try:
        return datetime.fromisoformat(ts.replace("Z", "+00:00")).date().isoformat()
    except ValueError:
        return ""


def to_int(value):
    if value in (None, ""):
        return 0
    try:
        return int(value)
    except ValueError:
        return 0


def build_summary(rows):
    grouped = defaultdict(lambda: {
        "request_count": 0,
        "success_count": 0,
        "error_count": 0,
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0,
    })

    for row in rows:
        key = (
            to_date(row.get("timestamp_utc", "")),
            row.get("topic", ""),
            row.get("round_label", ""),
            row.get("team", ""),
            row.get("stage", ""),
            row.get("model", ""),
        )
        bucket = grouped[key]
        bucket["request_count"] += 1
        if row.get("status", "") == "success":
            bucket["success_count"] += 1
        else:
            bucket["error_count"] += 1

        bucket["prompt_tokens"] += to_int(row.get("prompt_tokens"))
        bucket["completion_tokens"] += to_int(row.get("completion_tokens"))
        bucket["total_tokens"] += to_int(row.get("total_tokens"))

    summary_rows = []
    for key, stats in sorted(grouped.items()):
        date, topic, round_label, team, stage, model = key
        summary_rows.append(
            {
                "date": date,
                "topic": topic,
                "round_label": round_label,
                "team": team,
                "stage": stage,
                "model": model,
                **stats,
            }
        )

    return summary_rows


def write_summary(path, rows):
    fields = [
        "date",
        "topic",
        "round_label",
        "team",
        "stage",
        "model",
        "request_count",
        "success_count",
        "error_count",
        "prompt_tokens",
        "completion_tokens",
        "total_tokens",
    ]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def build_prompts(rows):
    prompt_rows = []
    for row in rows:
        if not row.get("user_prompt", "").strip():
            continue
        prompt_rows.append(
            {
                "timestamp_utc": row.get("timestamp_utc", ""),
                "session_id": row.get("session_id", ""),
                "topic": row.get("topic", ""),
                "round_label": row.get("round_label", ""),
                "team": row.get("team", ""),
                "stage": row.get("stage", ""),
                "status": row.get("status", ""),
                "user_prompt": row.get("user_prompt", ""),
            }
        )
    return prompt_rows


def write_prompts(path, rows):
    fields = [
        "timestamp_utc",
        "session_id",
        "topic",
        "round_label",
        "team",
        "stage",
        "status",
        "user_prompt",
    ]
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def main():
    args = parse_args()
    rows = load_rows(args.input)

    summary_rows = build_summary(rows)
    write_summary(args.summary_output, summary_rows)

    prompt_rows = build_prompts(rows)
    write_prompts(args.prompts_output, prompt_rows)

    print(f"Wrote summary: {args.summary_output} ({len(summary_rows)} rows)")
    print(f"Wrote prompts: {args.prompts_output} ({len(prompt_rows)} rows)")


if __name__ == "__main__":
    main()
